version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5431:5432"
  apigateway:
    build: './src/apigateway'
    restart: always
    ports:
      - "8080:8080"
    environment:
      BONUS_BASEURL: 'http://bonus_service:8050/api/v1'
      TICKET_BASEURL: 'http://ticket_service:8070/api/v1'
      FLIGHT_BASEURL: 'http://flight_service:8060/api/v1'
  ticket_service:
    build: './src/ticket_service'
    restart: always
    ports:
      - "8070:8070"
    environment:
      DB_USER: 'program'
      DB_PASSWORD: 'test'
      DB_HOST: 'postgres'
      DB_NAME: 'tickets'
  flight_service:
    build: './src/flight_service'
    restart: always
    ports:
      - "8060:8060"
    environment:
      DB_USER: 'program'
      DB_PASSWORD: 'test'
      DB_HOST: 'postgres'
      DB_NAME: 'flights'
  bonus_service:
    build: './src/bonus_service'
    restart: always
    ports:
      - "8050:8050"
    environment:
      DB_USER: 'program'
      DB_PASSWORD: 'test'
      DB_HOST: 'postgres'
      DB_NAME: 'privileges'

# TODO добавить сервисы

volumes:
  db-data: